- name: Step 00xxxxx post software
  hosts: support
  gather_facts: False
  become: yes
  tasks:
    - debug:
        msg: "Post-Software tasks Started"

- name: Step lab post software deployment
  hosts: bastions
  gather_facts: False
  become: yes
  tags:
    - opentlc_bastion_tasks
  tasks:
    - import_role:
        name: "bastion-opentlc-ipa"
      when: install_ipa_client|bool

    # sssd bug, fixed by restart
    - name: restart sssd
      service:
        name: sssd
        state: restarted
      when: install_ipa_client

- name: Set user info and data
  hosts: workstation
  tasks:
    - name: Set workstation public ip address user data
      agnosticd_user_info:
        data:
          rhel8lab_workstation_public_ip_address: "{{ public_ip_address }}"
          bookbag_os_auth_url: "{{ osp_auth_url }}"
          bookbag_os_username: "{{ guid }}-user"
          bookbag_os_password: "{{ hostvars.localhost.heat_user_password }}"
          bookbag_os_project_name: "{{ guid }}-project"
          
# for testing user info, from
# https://github.com/redhat-cop/agnosticd/blob/d4e62c36ce7b55422aaca3adbb0db3b115faaab7/ansible/configs/ocp4-cluster/post_software.yml#L293-L315
- name: Step 005.6 Print Student Info
  hosts: localhost
  gather_facts: false
  become: false
  tasks:
  - name: Print Student Information
    when: install_student_user | bool
    block:
    - name: Store bastion hostname as a fact
      set_fact:
        bastion_hostname: "{{groups['bastions'].0 }}"
    - name: print out user.info
      debug:
        msg: "{{ item }}"
      loop:
      - "user.info: You can access your bastion via SSH:"
      - "user.info: ssh {{ student_name }}@bastion.{{ guid }}{{ subdomain_base_suffix if cloud_provider == 'ec2' else '.'+ocp4_base_domain }}"
      - "user.info: "
      - "user.info: Make sure you use the username '{{ student_name }}' and the password '{{ hostvars[bastion_hostname]['student_password'] }}' when prompted."
    - name: print out user.info
      debug:
        msg: "user.info: kubeadmin password {{ hostvars[bastion_hostname]['kubeadmin_password']['content'] | b64decode }}"
      when: cloud_provider == "azure" or cloud_provider == "gcp"

# for testing, from https://github.com/redhat-cop/agnosticd/blob/development/ansible/configs/osp-sandbox/post_software.yml
- name: print out user.info
  debug:
    msg: "{{ item }}"
  loop:
    - "user.info: You can access your bastion via SSH:"
    - "user.info: ssh {{ student_name }}@bastion.{{ guid }}.{{ osp_cluster_dns_zone }}"
    - "user.info: "
    - "user.info: Make sure you use the username '{{ student_name }}' and the password '{{ hostvars['bastion']['student_password'] }}' when prompted."
    - "user.info: "
    - "user.info: Your base domain is '{{ student_dns_zone | default(osp_cluster_dns_zone) }}'"
    - "user.info: "
    - "user.info: For reference, the data you need to create your clouds.yaml file is:"
    - "user.info: "
    - "user.info: clouds:"
    - "user.info:   {{ osp_project_name }}:"
    - "user.info:     auth:"
    - "user.info:       auth_url: {{ osp_auth_url }}"
    - "user.info:       username: {{ guid }}-user"
    - "user.info:       project_name: {{ osp_project_name }}"
    - "user.info:       project_id: {{ hostvars['localhost']['osp_project_info'][0].id }}"
    - "user.info:       user_domain_name: Default"
    - "user.info:       password: {{ hostvars['localhost']['heat_user_password'] }}"
    - "user.info:     region_name: regionOne"
    - "user.info:     interface: public"
    - "user.info:     identity_api_version: 3"

- name: PostSoftware flight-check
  hosts: localhost
  connection: local
  gather_facts: false
  become: false
  tags:
    - post_flight_check
  tasks:
    - debug:
        msg: "Post-Software checks completed successfully"
