---
- name: Step 00xxxxx software
  hosts: localhost
  gather_facts: False
  become: false
  tasks:
    - debug:
        msg: "Software tasks Started"

- name: unregister from Satellite
#  hosts: node1
  hosts: all
  become: yes
  tasks:
    - name: call module to unregister
      redhat_subscription:
        state: absent

#xxx
#
#    - name: fix permission
#      file:
#        path: "{{output_dir}}/{{env_authorized_key}}"
#        mode: 0400
#      when: set_env_authorized_key | bool
#
#xxx

- name: Software flight-check
  hosts: localhost
  connection: local
  gather_facts: false
  become: false
  tags:
    - post_flight_check
  tasks:
    - debug:
        msg: "Software checks completed successfully"
